#############################################################################
# Makefile for building: bin/migraine
# Generated by qmake (2.01a) (Qt 4.4.3) on: Thu Nov 6 18:09:18 2008
# Project:  migraine.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile migraine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include/QtGui -I/usr/include/QtXml -I/usr/include/QtXml -I/usr/include/QtSql -I/usr/include/QtSql -I/usr/include -Ibuild -Ibuild
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSql -L/usr/lib -pthread -pthread -lQtXml -pthread -pthread -lQtGui -L/usr/X11R6/lib -pthread -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/migrainemainwindow.cpp \
		src/main.cpp \
		src/connectiondialog.cpp build/moc_migrainemainwindow.cpp \
		build/moc_connectiondialog.cpp
OBJECTS       = build/migrainemainwindow.o \
		build/main.o \
		build/connectiondialog.o \
		build/moc_migrainemainwindow.o \
		build/moc_connectiondialog.o
DIST          = /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		migraine.pro
QMAKE_TARGET  = migraine
DESTDIR       = bin/
TARGET        = bin/migraine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_migrainewindow.h build/ui_connectiondialog.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: migraine.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/g++.conf \
		/usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/lib/libQtSql.prl \
		/usr/lib/libQtCore.prl \
		/usr/lib/libQtXml.prl \
		/usr/lib/libQtGui.prl
	$(QMAKE) -unix -o Makefile migraine.pro
/usr/share/qt/mkspecs/common/g++.conf:
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/lib/libQtSql.prl:
/usr/lib/libQtCore.prl:
/usr/lib/libQtXml.prl:
/usr/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile migraine.pro

dist: 
	@$(CHK_DIR_EXISTS) build/migraine1.0.0 || $(MKDIR) build/migraine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/migraine1.0.0/ && $(COPY_FILE) --parents src/migrainemainwindow.h src/connectiondialog.h build/migraine1.0.0/ && $(COPY_FILE) --parents src/migrainemainwindow.cpp src/main.cpp src/connectiondialog.cpp build/migraine1.0.0/ && $(COPY_FILE) --parents ui/migrainewindow.ui ui/connectiondialog.ui build/migraine1.0.0/ && (cd `dirname build/migraine1.0.0` && $(TAR) migraine1.0.0.tar migraine1.0.0 && $(COMPRESS) migraine1.0.0.tar) && $(MOVE) `dirname build/migraine1.0.0`/migraine1.0.0.tar.gz . && $(DEL_FILE) -r build/migraine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_migrainemainwindow.cpp build/moc_connectiondialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_migrainemainwindow.cpp build/moc_connectiondialog.cpp
build/moc_migrainemainwindow.cpp: build/ui_migrainewindow.h \
		src/migrainemainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/migrainemainwindow.h -o build/moc_migrainemainwindow.cpp

build/moc_connectiondialog.cpp: build/ui_connectiondialog.h \
		src/connectiondialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) src/connectiondialog.h -o build/moc_connectiondialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_migrainewindow.h build/ui_connectiondialog.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_migrainewindow.h build/ui_connectiondialog.h
build/ui_migrainewindow.h: ui/migrainewindow.ui
	/usr/bin/uic ui/migrainewindow.ui -o build/ui_migrainewindow.h

build/ui_connectiondialog.h: ui/connectiondialog.ui
	/usr/bin/uic ui/connectiondialog.ui -o build/ui_connectiondialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/migrainemainwindow.o: src/migrainemainwindow.cpp src/migrainemainwindow.h \
		build/ui_migrainewindow.h \
		src/connectiondialog.h \
		build/ui_connectiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/migrainemainwindow.o src/migrainemainwindow.cpp

build/main.o: src/main.cpp src/migrainemainwindow.h \
		build/ui_migrainewindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/connectiondialog.o: src/connectiondialog.cpp src/connectiondialog.h \
		build/ui_connectiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/connectiondialog.o src/connectiondialog.cpp

build/moc_migrainemainwindow.o: build/moc_migrainemainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_migrainemainwindow.o build/moc_migrainemainwindow.cpp

build/moc_connectiondialog.o: build/moc_connectiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_connectiondialog.o build/moc_connectiondialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

